name: SAST

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# This section configures the trigger for the workflow. Feel free to customize depending on your convention
jobs:

  compile:
    runs-on: ubuntu-latest
    name: Running Java ${{ matrix.java }} compile
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
          java-version: 11.0.4
    - name: Build with maven
      run: mvn -B package --file pom.xml
 
  
  Scan-Build:      
    runs-on: ubuntu-latest
    needs: compile
    steps:
    - uses: actions/checkout@v1
    - name: Perform ShiftLeft Scan
      uses: ShiftLeftSecurity/scan-action@master
      with:
        output: reports
      env:
        WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCAN_AUTO_BUILD: false
        SCAN_DEBUG_MODE: debug
    - name: Upload scan reports
      uses: actions/upload-artifact@v1.0.0
      with:
        name: shiftleft-scan-reports
        path: reports
